"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const bookData_1 = require("./bookData");
const main_1 = require("./main");
const books = bookData_1.popularBooks;
const members = bookData_1.members;
const MyLib = new main_1.Library([], []);
books.map(book => MyLib.addBook(book));
members.map(member => MyLib.addMember(member));
const newMember = { memberId: "M004", name: "Diana Miller", phone: "555-3456", borrowedBooks: [] };
MyLib.addMember(newMember);
MyLib.borrowBook("M004", 3);
MyLib.returnBook("M004", 3);
console.log(MyLib.members[1]);
